main:
  project_name: CustomerChurnAI 
  experiment_name: development
  steps: all
  ip_address: 127.0.0.1
  port: 8000
etl:
  sample: "dataset.csv"
data_check:
  kl_threshold: 0.2
modeling:
  test_size: 0.2
  val_size: 0.2
  random_seed: 42
  stratify_by: Churn
  n_jobs: -1
  random_forest:
    n_estimators: [50, 100, 200]
    max_depth: [5, 10, 15, 20]
    min_samples_split: [2, 4, 8]
    min_samples_leaf: [1, 2, 3]
    max_features: [0.33, 0.5]
    criterion: ["gini", "entropy", "log_loss"]      
