name: Customer Churn CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

      # --------------------------------------------------
      # 1. Checkout repository
      # --------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --------------------------------------------------
      # 2. Set up Miniconda
      # --------------------------------------------------
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.13"
          auto-activate-base: true

      # --------------------------------------------------
      # 3. Install CI dependencies
      # --------------------------------------------------
      - name: Install CI dependencies
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==3.3.2
          pip install flake8
          pip install wandb==0.21.3

      # --------------------------------------------------
      # 4. Configure W&B
      # --------------------------------------------------
      - name: Configure W&B
        shell: bash -el {0}
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          wandb login "$WANDB_API_KEY"

      # --------------------------------------------------
      # 5. Flake8
      # --------------------------------------------------
      - name: Run Flake8
        shell: bash -el {0}
        run: |
          flake8 . \
            --count \
            --select=E9,F63,F7,F82 \
            --show-source \
            --statistics

      # --------------------------------------------------
      # 6. Data tests
      # --------------------------------------------------
      - name: Run data tests
        shell: bash -el {0}
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          mlflow run . -P steps=test_data

      # --------------------------------------------------
      # 7. Model performance tests
      # --------------------------------------------------
      - name: Run model tests
        shell: bash -el {0}
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          mlflow run . -P steps=test_model

      # --------------------------------------------------
      # 8. FastAPI tests
      # --------------------------------------------------
      - name: Run API tests
        shell: bash -el {0}
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          mlflow run . -P steps=test_api
